#ifndef ERRORCODES_H 
#define ERRORCODES_H 

#include "macros.h"

enum error_codes {
	/* Lexer */
	LEXER_ERR_EMPTY_INPUT,
	/* Pre-processor */
	PREPROC_ERR_INVALID_DIRECTIVE,
	PREPROC_ERR_UNCLOSED_PARENTHESIS,
	PREPROC_ERR_UNCLOSED_ANGLEBRACKET,
	PREPROC_ERR_EXPECTED_NAME_SYMBOL,
	PREPROC_ERR_EXPECTED_STRING_OR_ANGLEBRACKET,

	/* Structurizer */
	STRUCT_ERR_STRAY_BRACKET,
	STRUCT_ERR_STRAY_PARENTHESIS,
	STRUCT_ERR_STRAY_CURLYBRACE,

	/* Float-To-Int converter */

	/* Compiler */

	/* Assembler */

};

#endif